### ISSUE TITLE
跨域可以用nginx，配置还简单，用django看你写了一大陀

### ISSUE THREAD

**Issue by ihgoo** [HuberTRoy/vue-shiyanlou#5]

**Comment by HuberTRoy** [comment]
跨域用Nginx和Django都是简单的方式，Nginx配置一下响应头，Django加一个装饰器。

有点事后诸葛亮的情况来说，实验楼后面加了token验证，这个token无法由纯前端获取，只能借助一个后端语言。

**Comment by ihgoo** [comment]
刚才看了下，还真是的。。。header里面的auth值(x-syl-client-token)是在服务端用Nuxt渲染出来的，确实没法通过简单配置的用nginx跨域。
